---
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/first-interaction@v1
        with:
          issue-message: "Hello @${{ github.actor }} , thank you for submitting an issue I'll reply to it as quickly as I can!!"
          pr-message: "Hello @${{ github.actor }} , thank you submitting a pull request!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
    true: pull_request
name: Greetings
on: 
  - pull_request
  - issues
